import type { CampaignLocationSource } from '../types';

export const CROWS_DEN_CAMPAIGN_LOCATION: CampaignLocationSource = {
  locationId: '11',
  slug: 'crows-den',
  title: "The Crow's Den",
  densityTargets: {
    minVisibleEncounters: 8,
    minVisibleMonsters: 3,
    sections: {
      '00_setting': { min: 3, max: 5 },
      '10_plot': { min: 4, max: 6 },
      '20_characters': { min: 4, max: 8 },
      '30_monsters': { min: 4, max: 6, visibleMin: 3 },
      '40_places': { min: 6, max: 10 },
      '50_items': { min: 4, max: 8 },
      '60_shops_services': { min: 1, max: 3 },
      '70_factions': { min: 2, max: 5 },
      '80_encounters': { min: 10, max: 12, visibleMin: 8 },
      '90_rules_guidance': { min: 3, max: 5 },
    },
  },
  ipPolicy: {
    originalityReviewRequired: true,
    approvedBy: null,
    approvalDate: null,
    notes: 'Production metadata migration is deferred until narrative/product approval ownership is recorded.',
  },
  defaults: {
    arcSummary: "Crow's Den is a tavern, rookery, and threshold house where bargains echo through shutters, casks, feathers, and old salt lines.",
    currentStakes: 'The room must learn which bargain has woken the rafters before the threshold chooses a side.',
    openingDecision: {
      id: 'crows-den-opening-choice',
      prompt: 'The black bell trembles above the common room while the cellar stair exhales cold ale-scented air. What do the characters test first?',
      options: [
        {
          id: 'answer-the-bell',
          label: 'Answer the bell',
          summary: 'Touch the rope, listen to the rafters, and risk being named by whatever answers.',
        },
        {
          id: 'salt-the-threshold',
          label: 'Salt the threshold',
          summary: 'Repair the broken salt line and decide who must stand outside it.',
        },
        {
          id: 'descend-the-stair',
          label: 'Descend the cellar stair',
          summary: 'Follow the cold breath below and ask why the casks have begun to hum.',
        },
      ],
    },
    discoveries: [
      'The shutters count names by opening once for each oath spoken aloud.',
      'Old salt under the door blackens when a false bargain crosses it.',
      'The cellar casks answer in chorus when the bell rope moves without a hand.',
    ],
    clocks: [
      {
        id: 'black-bell-answers',
        label: 'Black bell answers',
        value: 1,
        max: 6,
        summary: 'Each ignored omen lets the bell speak with a clearer voice from the rafters.',
      },
      {
        id: 'threshold-picks-a-side',
        label: 'Threshold picks a side',
        value: 0,
        max: 6,
        summary: 'Every broken bargain teaches the tavern which guests it should keep close.',
      },
    ],
  },
  entries: [
    {
      id: '00.11.tavern-rookery-threshold',
      kind: 'setting',
      title: 'Tavern, rookery, threshold',
      summary: "Crow's Den is warm at the tables, cold at the shutters, and watchful in the rafters where feathers settle into old names.",
      tags: ['tavern', 'rookery', 'threshold', 'rafters'],
      sensoryAnchors: ['ale steam', 'salt grit', 'wing beats behind closed shutters'],
    },
    {
      id: '00.12.black-bell',
      kind: 'setting',
      title: 'The black bell over the bar',
      summary: 'The black bell hangs from a rope of braided hair and cask wire, sounding softly when a guest lies about what they brought in.',
      tags: ['bell', 'bar', 'omen'],
      relatedEntryIds: ['80.11.black-bell-toll', '30.13.bell-rope-thresher'],
    },
    {
      id: '00.13.salt-threshold',
      kind: 'setting',
      title: 'Salt threshold',
      summary: 'A dark salt line rings the main door, broken in three places by old boot marks and fresh feather prints.',
      tags: ['salt', 'door', 'threshold'],
      relatedEntryIds: ['80.12.salt-line-breaks'],
    },
    {
      id: '10.11.opening-bargain',
      kind: 'plot',
      title: 'The unpaid feather bargain',
      summary: 'Someone promised the rafters a name, a secret, or a warm seat by the fire; the promise has come due during the current gathering.',
      tags: ['bargain', 'secret', 'pressure'],
      pressure: 'Ask who benefited from the old promise and what they will offer instead.',
      nextQuestions: ['Who remembers making the bargain?', 'Which sign points to the original witness?'],
      relatedEntryIds: ['70.11.roof-ledger', '20.11.marn-caskwarden'],
    },
    {
      id: '10.12.scenario-after-hours',
      kind: 'scenario_prompt',
      title: 'After-hours door that should not open',
      summary: 'When the last candle gutters, a second tavern door appears inside the first and shows a rain-soaked road none of the guests recall taking.',
      tags: ['door', 'road', 'threshold'],
      relatedEntryIds: ['40.11.inner-threshold-door', '80.18.threshold-wager'],
    },
    {
      id: '10.13.roof-witness-demand',
      kind: 'plot',
      title: 'The roof asks for a witness',
      summary: 'The rafters refuse to quiet until someone names who stood nearest the first bargain and what they carried away.',
      tags: ['witness', 'rafters', 'bargain'],
      pressure: 'Put an uncertain witness in the center of the room before the bell chooses one.',
      nextQuestions: ['Which guest was present but silent?', 'What object proves the order of promises?'],
      relatedEntryIds: ['70.11.roof-ledger', '40.14.private-rookery-screen'],
    },
    {
      id: '10.14.last-cup-on-table',
      kind: 'plot',
      title: 'The last cup has no owner',
      summary: 'A filled cup remains after every guest denies ordering it, and its reflection shows one seat still waiting.',
      tags: ['cup', 'memory', 'seat'],
      pressure: 'Use the unclaimed cup to reveal whose absence is shaping the gathering.',
      nextQuestions: ['Who refuses the seat?', 'Which memory appears in the cup first?'],
      relatedEntryIds: ['80.20.mirror-ale-reflection', '50.13.unclaimed-black-cup'],
    },
    {
      id: '20.11.marn-caskwarden',
      kind: 'npc',
      title: 'Marn Caskwarden',
      summary: 'Marn tends the bar with one ear pressed to the casks and writes every unpaid favor on bottle glass instead of paper.',
      tags: ['keeper', 'bar', 'casks'],
      motive: 'Keep the tavern open without letting the rafters choose another keeper.',
      secret: 'Marn knows which guest traded a name to the roof ledger.',
      tells: ['rubs salt into the same palm', 'never turns their back on the bell'],
      relatedEntryIds: ['50.11.bottle-glass-ledger', '80.16.cask-choir-hum'],
    },
    {
      id: '20.12.avel-of-the-shutters',
      kind: 'npc',
      title: 'Avel of the Shutters',
      summary: 'Avel repairs every shutter from inside the room and swears the outside view changes when no one is watching.',
      tags: ['shutters', 'witness', 'repair'],
      motive: 'Prove the shutters are counting guests before the count completes.',
      secret: 'Avel has hidden one counted name under a loose hinge.',
      relatedEntryIds: ['40.12.counting-shutters', '80.14.shutters-count-names'],
    },
    {
      id: '20.13.sister-vale',
      kind: 'npc',
      title: 'Sister Vale with the ash veil',
      summary: 'Sister Vale buys silence with candle stubs and asks each traveler which road they would refuse to take again.',
      tags: ['candle', 'road', 'confessor'],
      motive: 'Find the guest whose refused road now waits behind the threshold.',
      relatedEntryIds: ['10.12.scenario-after-hours', '80.18.threshold-wager'],
    },
    {
      id: '20.14.orren-thrice-dry',
      kind: 'npc',
      title: 'Orren Thrice-Dry',
      summary: 'Orren sits near the coldest wall with three untouched cups and claims each was poured for a different version of the same night.',
      tags: ['cup', 'memory', 'witness'],
      motive: 'Leave the tavern with one true version of the bargain intact.',
      secret: 'Orren knows why the inner door shows a road in rain.',
      tells: ['counts cups before answering', 'watches reflections instead of faces'],
      relatedEntryIds: ['10.14.last-cup-on-table', '50.13.unclaimed-black-cup'],
    },
    {
      id: '30.11.shutter-crow-host',
      kind: 'monster',
      title: 'Shutter Crow Host',
      summary: 'A braided flock that moves like one guest-sized shadow when the shutters clap in sequence.',
      tags: ['crow', 'shutters', 'swarm', 'threat'],
      sensorySigns: ['wet feather smell', 'three taps from every latch', 'many small eyes in one dark pane'],
      behavior: 'Tests who will break formation by whispering borrowed names from the window seams',
      lairOrHaunt: 'Window banks and coat pegs near the salt threshold',
      hungerOrDesire: 'Wants a spoken name to carry into the rafters',
      tactics: ['separates guests from doorways', 'mimics familiar voices from behind shutters'],
      fearsOrLimits: ['hesitates at fresh salt', 'scatters when the bell is answered honestly'],
      encounterRoles: ['ambusher', 'omen carrier'],
      relatedEntryIds: ['80.14.shutters-count-names', '00.13.salt-threshold'],
    },
    {
      id: '30.12.cellar-cask-choir',
      kind: 'monster',
      title: 'Cellar Cask Choir',
      summary: 'A row of casks that speaks as one throat and rolls nearer whenever someone refuses a truthful answer.',
      tags: ['casks', 'cellar', 'chorus', 'threat'],
      sensorySigns: ['staves flexing like ribs', 'ale foam forming letters', 'humming below the floorboards'],
      behavior: 'Offers answers in exchange for embarrassing truths and grows louder around withheld promises',
      lairOrHaunt: 'The cellar stair and the wet stones below it',
      hungerOrDesire: 'Wants secrets poured into it until the tavern remembers them as fact',
      tactics: ['blocks narrow steps', 'drowns out lies with chorus noise'],
      fearsOrLimits: ['quieted by shared confession', 'cannot cross a dry chalk ring'],
      encounterRoles: ['social pressure', 'cellar obstacle'],
      relatedEntryIds: ['80.13.cellar-stair-breathes', '80.16.cask-choir-hum'],
    },
    {
      id: '30.13.bell-rope-thresher',
      kind: 'monster',
      title: 'Bell-Rope Thresher',
      summary: 'The bell rope knots into a long jointed shape that drags chairs into a circle and waits for a hand to pull it.',
      tags: ['bell', 'rope', 'bar', 'threat'],
      sensorySigns: ['braid tightening by itself', 'bar hooks chiming out of rhythm', 'chairs scraping inward'],
      behavior: 'Punishes hesitation by tightening the room around one visible choice',
      lairOrHaunt: 'Above the bar beam, wrapped around the black bell hook',
      hungerOrDesire: 'Wants a guest to answer a summons aloud',
      tactics: ['controls the center aisle', 'cuts off the easiest route to the bar'],
      fearsOrLimits: ['loosens when two rivals pull together', 'will not cross the cellar stair'],
      encounterRoles: ['center-room pressure', 'combat-ready anchor'],
      relatedEntryIds: ['00.12.black-bell', '80.11.black-bell-toll'],
    },
    {
      id: '30.14.ash-feather-matron',
      kind: 'monster',
      title: 'Ash-Feather Matron',
      summary: 'A tall shape behind the rookery screen arranges loose feathers into family crests that no guest wants to recognize.',
      tags: ['rookery', 'feathers', 'hidden', 'bargain'],
      revealConditions: ['discovery:roof-ledger-matron'],
      sensorySigns: ['warm ash drifting upward', 'a veil of feathers moving against the draft'],
      behavior: 'Offers to settle disputes by naming the person each guest fears owing most',
      lairOrHaunt: 'The screened loft above the private table',
      hungerOrDesire: 'Wants old obligations acknowledged in public',
      fearsOrLimits: ['cannot speak while the black bell is still'],
      encounterRoles: ['revealed negotiator', 'late-scene pressure'],
      relatedEntryIds: ['70.11.roof-ledger', '80.15.rookery-table-offering'],
    },
    {
      id: '40.11.inner-threshold-door',
      kind: 'place',
      title: 'Inner threshold door',
      summary: 'A second door sometimes appears within the first, opening onto a road where wet footprints walk toward the tavern instead of away.',
      tags: ['door', 'road', 'threshold'],
      features: ['double frame', 'wet footprints', 'cold latch'],
      routes: ['main room', 'unknown road'],
      relatedEntryIds: ['10.12.scenario-after-hours', '80.18.threshold-wager'],
    },
    {
      id: '40.12.counting-shutters',
      kind: 'place',
      title: 'Counting shutters',
      summary: 'The shutters open and close by count, matching guests to promises no one admits making.',
      tags: ['shutters', 'windows', 'count'],
      relatedEntryIds: ['20.12.avel-of-the-shutters', '30.11.shutter-crow-host'],
    },
    {
      id: '40.13.cellar-stair',
      kind: 'place',
      title: 'Cellar stair under the loose rug',
      summary: 'The stair descends beneath a rug stitched with feather marks, and every third step sounds hollow even when no foot touches it.',
      tags: ['cellar', 'stair', 'casks'],
      relatedEntryIds: ['30.12.cellar-cask-choir', '80.13.cellar-stair-breathes'],
    },
    {
      id: '40.14.private-rookery-screen',
      kind: 'place',
      title: 'Private rookery screen',
      summary: 'A folding screen of cracked lacquer and pinned feathers hides a loft ladder that creaks only when a bargain is remembered.',
      tags: ['rookery', 'screen', 'loft'],
      features: ['pinned feathers', 'hidden ladder', 'scratched lacquer'],
      routes: ['private table', 'screened loft'],
      relatedEntryIds: ['30.14.ash-feather-matron', '80.15.rookery-table-offering'],
    },
    {
      id: '40.15.hearth-ash-circle',
      kind: 'place',
      title: 'Hearth ash circle',
      summary: 'Ash around the hearth forms a gray ring where guests can speak refusals without the shutters repeating them.',
      tags: ['hearth', 'ash', 'refusal'],
      features: ['gray ring', 'warm stones', 'quiet center'],
      routes: ['common room', 'private table'],
      relatedEntryIds: ['20.13.sister-vale', '90.13-refusal-guidance'],
    },
    {
      id: '40.16.back-room-witness-nook',
      kind: 'place',
      title: 'Back-room witness nook',
      summary: 'A narrow nook behind stacked chairs keeps one listener close enough to hear the bar but hidden from the bell rope.',
      tags: ['witness', 'back-room', 'chairs'],
      features: ['stacked chairs', 'narrow view', 'muted bell sound'],
      routes: ['bar', 'service room'],
      relatedEntryIds: ['60.11.marns-quiet-favors', '10.13.roof-witness-demand'],
    },
    {
      id: '50.11.bottle-glass-ledger',
      kind: 'item',
      title: 'Bottle-glass ledger',
      summary: 'Marn records favors on green bottle shards that rearrange themselves when the black bell stirs.',
      tags: ['ledger', 'glass', 'favor'],
      use: 'Hold a shard to firelight to see which favor has changed hands.',
      costSignal: 'The shard warms when a character offers a true name or a true refusal.',
      relatedEntryIds: ['20.11.marn-caskwarden', '70.11.roof-ledger'],
    },
    {
      id: '50.12.rookery-salt-bowl',
      kind: 'item',
      title: 'Rookery salt bowl',
      summary: 'A cracked bowl of black salt sits by the door, always lighter after a bargain crosses the threshold.',
      tags: ['salt', 'bowl', 'threshold'],
      relatedEntryIds: ['00.13.salt-threshold', '80.12.salt-line-breaks'],
    },
    {
      id: '50.13.unclaimed-black-cup',
      kind: 'item',
      title: 'Unclaimed black cup',
      summary: 'A black cup refills only when no one is looking and reflects the room one promise earlier than the present moment.',
      tags: ['cup', 'memory', 'reflection'],
      use: 'Set the cup between two disputed witnesses and watch which reflection turns away first.',
      costSignal: 'The cup chills when a guest refuses to own the memory inside it.',
      relatedEntryIds: ['10.14.last-cup-on-table', '80.20.mirror-ale-reflection'],
    },
    {
      id: '50.14.ash-veiled-candle',
      kind: 'item',
      title: 'Ash-veiled candle',
      summary: 'A short candle burns with a dull gray flame and leaves soot marks pointing toward the person avoiding a refusal.',
      tags: ['candle', 'ash', 'refusal'],
      use: 'Light it during an argument to make the room focus on the unspoken refusal instead of the loudest accusation.',
      costSignal: 'The wick bends toward whoever wants the flame put out fastest.',
      relatedEntryIds: ['20.13.sister-vale', '40.15.hearth-ash-circle'],
    },
    {
      id: '60.11.marns-quiet-favors',
      kind: 'service',
      title: "Marn's quiet favors",
      summary: 'Marn can provide a private table, a hidden cup, or a back-room witness, but every favor must be named before the bell hears it.',
      tags: ['favor', 'table', 'witness'],
      provider: 'Marn Caskwarden',
      terms: 'A guest must offer a truthful account of why they need quiet.',
      relatedEntryIds: ['20.11.marn-caskwarden'],
    },
    {
      id: '70.11.roof-ledger',
      kind: 'faction',
      title: 'The Roof Ledger',
      summary: 'The rafters remember obligations as scratches in old beams and act through birds, shutters, and rope when a mark is ignored.',
      tags: ['rafters', 'bargain', 'rookery'],
      agenda: 'Collect acknowledged obligations without letting the tavern fall silent.',
      leverage: 'It can make witnesses appear unreliable by changing which sounds came first.',
      pressureSigns: ['fresh scratches over old initials', 'feathers arranged like tally marks'],
      relatedEntryIds: ['10.11.opening-bargain', '30.14.ash-feather-matron'],
    },
    {
      id: '70.12.threshold-keepers',
      kind: 'faction',
      title: 'Threshold Keepers',
      summary: 'Guests who repaired the salt line in earlier nights left small rules for who may enter, who may leave, and who must answer the bell.',
      tags: ['salt', 'threshold', 'rules'],
      agenda: 'Keep the tavern from becoming a road for every unfinished bargain.',
      leverage: 'Their old marks still strengthen fresh salt and quiet some shutter voices.',
      relatedEntryIds: ['00.13.salt-threshold', '80.12.salt-line-breaks'],
    },
    {
      id: '80.11.black-bell-toll',
      kind: 'encounter',
      title: 'Black bell toll',
      summary: 'The bell rings once without a hand and every cup on the table points toward the same guest.',
      tags: ['bell', 'choice', 'bar'],
      visibleTrigger: 'A lie, omission, or disputed promise is spoken near the bar',
      immediatePressure: 'The room waits for the named guest to answer or redirect the omen',
      playerFacingChoice: 'Answer the bell, accuse another witness, or silence the rope together',
      consequenceDirection: 'Truth steadies the room, evasion advances the bell clock, and blame draws the rafters closer',
      relatedEntryIds: ['00.12.black-bell', '30.13.bell-rope-thresher'],
    },
    {
      id: '80.12.salt-line-breaks',
      kind: 'hazard',
      title: 'Salt line breaks',
      summary: 'The black salt at the door splits into three thin gaps as cold air pushes feather prints inward.',
      tags: ['salt', 'door', 'hazard'],
      visibleTrigger: 'A guest steps across the door with an unresolved bargain',
      immediatePressure: 'The threshold starts deciding who belongs inside',
      playerFacingChoice: 'Repair the line, invite the pressure in, or move the gathering away from the door',
      consequenceDirection: 'Careful repair buys time while neglect lets the threshold choose harder terms',
      relatedEntryIds: ['00.13.salt-threshold', '50.12.rookery-salt-bowl'],
    },
    {
      id: '80.13.cellar-stair-breathes',
      kind: 'encounter',
      title: 'Cellar stair breathes',
      summary: 'The rug lifts as the stair below exhales cold ale breath and asks for the guest who promised to return.',
      tags: ['cellar', 'stair', 'casks'],
      visibleTrigger: 'The party studies the cellar rug or ignores cask sounds for too long',
      immediatePressure: 'The stair becomes the clearest route and the least trustworthy one',
      playerFacingChoice: 'Descend, bar the stair, or bargain with the voice below',
      consequenceDirection: 'Descent reveals leverage, delay strengthens the chorus, and bargaining exposes a secret',
      relatedEntryIds: ['40.13.cellar-stair', '30.12.cellar-cask-choir'],
    },
    {
      id: '80.14.shutters-count-names',
      kind: 'encounter',
      title: 'Shutters count names',
      summary: 'Each shutter clap matches a guest, but one extra clap lands after the room falls quiet.',
      tags: ['shutters', 'names', 'crow'],
      visibleTrigger: 'Characters argue about who is present or who can be trusted',
      immediatePressure: 'The unseen extra guest gains attention through sound alone',
      playerFacingChoice: 'Open a shutter, call the extra guest, or hide a name under salt',
      consequenceDirection: 'Opening reveals movement, calling invites an answer, and hiding a name changes who the flock follows',
      relatedEntryIds: ['40.12.counting-shutters', '30.11.shutter-crow-host'],
    },
    {
      id: '80.15.rookery-table-offering',
      kind: 'encounter',
      title: 'Rookery table offering',
      summary: 'A private table sets itself with three empty cups and a feather laid across each rim.',
      tags: ['table', 'rookery', 'offer'],
      visibleTrigger: 'The characters seek privacy, a pact, or a way to divide blame',
      immediatePressure: 'The table expects three offerings: a name, a refusal, and a promise',
      playerFacingChoice: 'Sit and answer, overturn the setting, or send one speaker to negotiate',
      consequenceDirection: 'Answering clarifies obligations, refusal angers the rafters, and negotiation reveals the hidden patron',
      relatedEntryIds: ['30.14.ash-feather-matron', '70.11.roof-ledger'],
    },
    {
      id: '80.16.cask-choir-hum',
      kind: 'encounter',
      title: 'Cask choir hum',
      summary: 'The cellar casks hum the same tune as the bell while foam writes a question along the stair wall.',
      tags: ['casks', 'cellar', 'question'],
      visibleTrigger: 'A character asks for information without offering truth in return',
      immediatePressure: 'The tavern offers an answer with a personal cost attached',
      playerFacingChoice: 'Read the foam, ask Marn to translate, or drown out the chorus with a shared song',
      consequenceDirection: 'Reading gives a clue, translation implicates Marn, and chorus work shifts attention from one guest to the group',
      relatedEntryIds: ['30.12.cellar-cask-choir', '20.11.marn-caskwarden'],
    },
    {
      id: '80.17.feather-tax-demand',
      kind: 'encounter',
      title: 'Feather tax demand',
      summary: 'Black feathers fall into every open palm, and the rafters wait for someone to pay attention with a confession.',
      tags: ['feathers', 'bargain', 'rafters'],
      visibleTrigger: 'The group tries to leave a dispute unresolved',
      immediatePressure: 'Each feather becomes heavier until someone names what they owe or refuse',
      playerFacingChoice: 'Confess, pass the feather, or burn one in candle flame',
      consequenceDirection: 'Confession redirects pressure, passing spreads suspicion, and burning marks a future visit from the roof ledger',
      relatedEntryIds: ['70.11.roof-ledger'],
    },
    {
      id: '80.18.threshold-wager',
      kind: 'encounter',
      title: 'Threshold wager',
      summary: 'The inner door shows a road from each character’s memory and asks which path should be barred from return.',
      tags: ['door', 'road', 'choice'],
      visibleTrigger: 'The party focuses on escape, pursuit, or a route that should not exist',
      immediatePressure: 'The room offers passage in exchange for a declared refusal',
      playerFacingChoice: 'Name the barred road, refuse the wager, or send a scout through the image',
      consequenceDirection: 'Naming creates a clear route with a cost, refusal keeps the room sealed, and scouting brings back an omen',
      relatedEntryIds: ['40.11.inner-threshold-door', '20.13.sister-vale'],
    },
    {
      id: '80.19.roof-scratch-procession',
      kind: 'encounter',
      title: 'Roof scratch procession',
      summary: 'A slow procession of scratches crosses the ceiling beam toward the bell hook.',
      tags: ['rafters', 'scratch', 'bell'],
      visibleTrigger: 'The party ignores the roof ledger or argues beneath the beam',
      immediatePressure: 'A partial name appears before anyone can agree who it accuses',
      playerFacingChoice: 'Stop the mark, finish it truthfully, or move the named guest from the beam',
      consequenceDirection: 'Stopping scatters signs, truth reveals leverage, and movement changes who the bell watches',
      relatedEntryIds: ['70.11.roof-ledger', '00.12.black-bell'],
    },
    {
      id: '80.20.mirror-ale-reflection',
      kind: 'encounter',
      title: 'Mirror ale reflection',
      summary: 'A dark pour in a cup reflects the room as it was one bargain ago instead of as it is now.',
      tags: ['ale', 'memory', 'cup'],
      visibleTrigger: 'Someone drinks, pours out a cup, or asks what changed first',
      immediatePressure: 'The reflection shows a contradiction one guest denies and another can prove',
      playerFacingChoice: 'Question it, compare it to the ledger, or break the cup before it changes',
      consequenceDirection: 'Questioning reveals sequence, comparison finds a witness, and breaking it chooses a new vessel',
      relatedEntryIds: ['50.11.bottle-glass-ledger', '20.11.marn-caskwarden'],
    },
    {
      id: '90.11.public-scene-guidance',
      kind: 'rules_guidance',
      title: "Crow's Den scene guidance",
      summary: 'Use bells, shutters, salt, casks, feathers, tables, doors, and ledgers as concrete pressure sources before introducing a direct threat.',
      tags: ['guidance', 'public-safe', 'scene'],
      do: ['Frame choices with visible omens', 'Let bargains complicate relationships', 'Keep consequences provisional and reversible'],
      avoid: ['Generic shadows', 'unearned certainty', 'private author notes'],
    },
    {
      id: '90.12.combat-handoff-guidance',
      kind: 'rules_guidance',
      title: 'Threat handoff guidance',
      summary: 'Escalate toward danger only after repeated omens or direct character action, and keep public narration focused on visible pressure.',
      tags: ['guidance', 'threat', 'handoff'],
      do: ['Use 80_encounters before 30_monsters', 'Name which anchor creates pressure', 'Keep agency with the players'],
      avoid: ['Instant outcomes', 'generic enemies', 'hidden scoring language'],
    },
    {
      id: '90.13-refusal-guidance',
      kind: 'rules_guidance',
      title: 'Refusal and bargain guidance',
      summary: 'Use refusals as active choices: a character may decline a bargain, but the tavern should visibly redirect pressure afterward.',
      tags: ['guidance', 'bargain', 'refusal'],
      do: ['Offer refusals with clear next pressure', 'Let witnesses change the meaning of a bargain', 'Tie each omen to a named anchor'],
      avoid: ['Single correct answers', 'faceless temptation', 'secret-only resolution'],
    },
  ],
  privateGameplayTemplates: [
    {
      id: 'template-bell-rope-thresher',
      sourceEntryIds: ['80.11.black-bell-toll', '30.13.bell-rope-thresher'],
      proposal: {
        title: 'Bell-Rope Thresher',
        summary: 'The bell rope controls the middle of the tavern while the party tries to break its hold.',
        difficulty: 'normal',
        monsterCount: 1,
        monsterName: 'Bell-Rope Thresher',
        monsterArchetype: 'controller',
        totalMonsterHp: 36,
        monsterAc: 13,
        monsterAttackBonus: 5,
        monsterDamageFormula: '1d8',
        sceneDc: 14,
        rewardXpPerCharacter: 0,
      },
    },
    {
      id: 'template-shutter-crow-host',
      sourceEntryIds: ['80.14.shutters-count-names', '30.11.shutter-crow-host'],
      proposal: {
        title: 'Shutter Crow Host',
        summary: 'A coordinated flock pressures doors and windows while the party protects the threshold.',
        difficulty: 'hard',
        monsterCount: 3,
        monsterName: 'Shutter Crow Host',
        monsterArchetype: 'skirmisher swarm',
        totalMonsterHp: 45,
        monsterAc: 12,
        monsterAttackBonus: 4,
        monsterDamageFormula: '1d6',
        sceneDc: 15,
        rewardXpPerCharacter: 0,
      },
    },
  ],
};
