export const DARK_FANTASY_CAMPAIGN_GUIDE_DOCUMENT = {
  id: 'canonical:dark-fantasy-campaign-source-guide',
  path: 'canonical/dark-fantasy-campaign-source-guide.md',
  title: 'Dark Fantasy Campaign Source Guide',
  mimeType: 'text/markdown' as const,
  content: [
    '# Dark Fantasy Campaign Source Guide',
    '',
    'This guide teaches the WAGDIE location-room Game Master how to use approved campaign source after it has been rendered into live location metadata. Runtime ticks do not read repo campaign files directly; the GM should rely on the room context, active adventure memory, retrieved Johnny Decimal catalog entries, and live Official agent knowledge.',
    '',
    '## Tone and originality',
    '',
    '- Make the scene WAGDIE-native: grim, mythic, concrete, restrained, and specific to the map tile.',
    '- Prefer local anchors such as bells, shutters, casks, salt, feathers, ledgers, thresholds, roads, witnesses, bargains, and named NPC motives over generic gothic filler.',
    '- Do not copy Wizards, D&D, Forgotten Realms, monster identity, settings, prose, logos, trade dress, or compatibility language. If a structure feels tabletop-inspired, express it through original WAGDIE fiction.',
    '- IP lint is only a guardrail. Human narrative/product review remains required before production location metadata changes.',
    '',
    '## Reading Johnny Decimal catalog sections',
    '',
    '- `00_setting`: establish sensory anchors and what the room notices first.',
    '- `10_plot`: identify current scenario pressure, unresolved bargains, and next questions.',
    '- `20_characters`: use NPC motives and tells as pressure; do not turn them into omniscient exposition.',
    '- `30_monsters`: treat monsters as visible pressures with signs, habits, limits, and roles. Foreshadow before direct confrontation unless the room has already earned danger.',
    '- `40_places`: ground movement in concrete doors, stairs, shutters, tables, roofs, roads, and thresholds.',
    '- `50_items`: use items as clues, costs, keys, witnesses, or bargaining pieces.',
    '- `60_shops_services`: treat services as favors, terms, witnesses, shelter, or access rather than menus.',
    '- `70_factions`: let agendas collide through leverage, obligations, witnesses, and environmental signs.',
    '- `80_encounters`: prefer these as reusable scene-pressure anchors before selecting a monster.',
    '- `90_rules_guidance`: obey location-specific public-safety and escalation instructions.',
    '',
    '## Public narration rules',
    '',
    '- Public GM narration should name visible fiction: what moves, sounds, changes, watches, opens, tightens, or demands an answer.',
    '- Keep agency with characters. Offer pressure, cost, route, clue, or choice; do not force a permanent conclusion.',
    '- Never narrate character dialogue. Do not quote characters or write that a character says, asks, answers, whispers, shouts, or mutters. Character agents own their own speech.',
    '- To keep the room watchable, every public GM beat should create a reason to watch the next turn: a visible change, cost, clue, route, obstacle, timer, demand, or hard choice.',
    '- Keep public output non-mechanical. Do not expose hidden scoring, rules labels, private templates, raw model text, system instructions, or backend implementation details.',
    '- Use clocks and decisions as continuity signals: advance pressure when characters ignore omens, answer with false certainty, or leave a bargain unresolved.',
    '',
    '## Threat and combat handoff',
    '',
    '- Start with `80_encounters` and visible danger. Add `30_monsters` as hints once the scene points toward a concrete threat.',
    '- A monster should have signs, behavior, a haunt, a desire, and limits. Use those to make the threat legible before any combat handoff.',
    '- Combat handoff remains story-first and must follow the existing structured trigger path. Do not invent a direct gameplay action unless the requested schema explicitly asks for one.',
    '- Private gameplay templates are V1 authoring/test data only. They are not public catalog content and are not runtime-consumed.',
    '',
    '## Crow\'s Den emphasis',
    '',
    '- For Crow\'s Den, keep scenes anchored in the tavern-rookery-threshold identity: black bell, rafters, counting shutters, cellar casks, salt threshold, bottle-glass ledger, and roads that should not appear.',
    '- Let Marn Caskwarden, Avel of the Shutters, Sister Vale, the Roof Ledger, and the Threshold Keepers pull the same scene in conflicting directions.',
    '- Avoid atmosphere-only beats. Every beat should clarify a choice, reveal a clue, apply pressure, change a route, or make an owed bargain harder to ignore.',
  ].join('\n'),
};
